#!/usr/bin/env python3
"""
Check Spotify app configuration and provide specific instructions
"""

print("🔍 Spotify App Configuration Check")
print("=" * 50)

print("The 403 error persists even with fresh tokens, which means the issue is with your Spotify app settings.")
print()
print("Here's what you need to check in your Spotify Developer Dashboard:")
print()
print("1. 🌐 Go to: https://developer.spotify.com/dashboard")
print("2. 🎯 Click on your ARAS app")
print("3. ⚙️  Go to 'Settings'")
print()
print("4. 👥 Check 'Users and Access' section:")
print("   - Make sure your email (arya.valizadeh@outlook.com) is listed")
print("   - If not, click 'Add New User' and add it")
print("   - Click 'Save' after adding")
print()
print("5. 🔧 Check 'App Status' section:")
print("   - Look for 'Development Mode' toggle")
print("   - If it's ON, try turning it OFF")
print("   - This makes the app public and removes user restrictions")
print()
print("6. 🔗 Verify 'Redirect URIs' section:")
print("   - Make sure this exact URI is listed:")
print("   - http://127.0.0.1:8080/callback")
print("   - If not, add it and click 'Save'")
print()
print("7. ⏰ Wait a few minutes after making changes")
print("   - Spotify sometimes takes time to propagate changes")
print()
print("8. 🧪 Test again by running:")
print("   python test_spotify_fix.py")
print()
print("If the issue persists, the problem might be:")
print("- Your Spotify account doesn't have Premium (required for Web API)")
print("- The app is in a restricted state")
print("- There's a delay in Spotify's system")
print()
print("Alternative solution:")
print("- Create a new Spotify app with a different name")
print("- Use the new app's credentials in your .env file")
print("- Re-authenticate with the new app")
